[theme]
base = "light"
primaryColor = "#0284c7"
backgroundColor = "#f0f9ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
